### ISSUE TITLE
【BUG】测试示例打开编译报错

### ISSUE THREAD

**Issue by zxzhgk** [dcloudio/UniApp#12]
详细问题描述

[内容]

[手机运行] D:\Hbuider\HBuilderX\plugins\fastapp\node_modules\uniapp-tools\webpack.config.js:68

[手机运行] throw new Error(
manifest.json中路由[${page}]的文件路径[${pagePath}]不存在，请及时删除
)

[手机运行] ^

[手机运行] 

[手机运行] Error: manifest.json中路由[Component/Div]的文件路径[undefined]不存在，请及时删除

[手机运行] at Object.keys.forEach.page (D:\Hbuider\HBuilderX\plugins\fastapp\node_modules\uniapp-tools\webpack.config.js:68:15)

[手机运行] at Array.forEach (<anonymous>)

[手机运行] at Object.<anonymous> (D:\Hbuider\HBuilderX\plugins\fastapp\node_modules\uniapp-tools\webpack.config.js:58:24)

[手机运行] at Module._compile (module.js:652:30)

[手机运行] at Object.Module._extensions..js (module.js:663:10)

[手机运行] at Module.load (module.js:565:32)

[手机运行] at tryModuleLoad (module.js:505:12)

[手机运行] at Function.Module._load (module.js:497:3)

[手机运行] at Module.require (module.js:596:17)

[手机运行] at require (internal/module.js:11:18)

[手机运行] 

[手机运行] 项目 'baobao' 编译失败.

运行环境

[系统版本] win10

[浏览器版本]

[IDE版本] 0.1.27.20180403-alpha

**Comment by xiaoyucoding** [comment]
整个删除 HBuilderX，在官网重新下一个试试。
